#!/bin/bash
# Change the following values to suit your local setup.
# Add this file on your .git/hooks/ and name it as 'pre-commit'
#
LOGTEXT="commit vérifié le " `date`
LOGPATH="suivi/commitInfo.txt"
read -p "Créer une ligne de verification de ce commit dans le log (y/[n]) ?" yn < /dev/tty
yn=${yn:n}
case $yn in
[Yy]* )
echo $LOGTEXT >> $LOGPATH
exit 0;;
[Nn]* )
exit 0;;
esac
exit 0
